apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "runners.fullname" . }}-config
  labels:
    {{- include "runners.labels" . | nindent 4 }}
data:
  runner-labels: {{ include "runners.labelsString" . | quote }}
  runner-group: {{ .Values.github.runnerGroup | quote }}
  runner-work-dir: {{ .Values.runner.workDir | quote }}
  runner-ephemeral: {{ .Values.runner.ephemeral | quote }}
