apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runners.fullname" . }}-github
  labels:
    {{- include "runners.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-url: {{ .Values.github.url | quote }}
  {{- if .Values.github.accessToken }}
  access-token: {{ .Values.github.accessToken | quote }}
  {{- else }}
  runner-token: {{ .Values.github.runnerToken | quote }}
  {{- end }}
