apiVersion: v1
kind: Service
metadata:
  name: {{ include "runners.fullname" . }}
  labels:
    {{- include "runners.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    {{- include "runners.selectorLabels" . | nindent 4 }}
